<?php

namespace App\Services;

use Illuminate\Support\Str;
use InvalidArgumentException;

class CampaignPageSanitizer
{
    /** @var array<int, string> */
    private array $allowedTags = [
        'a', 'article', 'aside', 'b', 'blockquote', 'br', 'button', 'del', 'details',
        'div', 'em', 'footer', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'header', 'hr',
        'i', 'img', 'li', 'main', 'mark', 'ol', 'p', 'picture', 'section', 'small',
        'source', 'span', 'strong', 'summary', 'sup', 'table', 'tbody', 'td', 'tfoot',
        'th', 'thead', 'tr', 'u', 'ul', 'video',
    ];

    /**
     * Sanitize the generated builder markup before it is published.
     * Builder pages deliberately do not accept executable tags or inline events.
     */
    public function html(?string $html): ?string
    {
        if ($html === null || trim($html) === '') {
            return null;
        }

        $html = str_replace("\0", '', $html);
        $html = preg_replace('/<\?(?:php|=)?[\s\S]*?\?>/i', '', $html) ?? '';

        // Preserve only the documented, non-executable storefront variables.
        $dynamicTokens = [];
        $html = preg_replace_callback(
            '/\{\{\s*((?:campaign|product|contact)\.(?:name|title|slug|deadline|description|image|price|old_price|discount|phone|whatsapp))\s*\}\}/i',
            function (array $match) use (&$dynamicTokens): string {
                $key = '___CPB_TOKEN_' . count($dynamicTokens) . '___';
                $dynamicTokens[$key] = '{{' . strtolower($match[1]) . '}}';
                return $key;
            },
            $html
        ) ?? '';
        $html = preg_replace('/\{!![\s\S]*?(?:!!\}|$)/', '', $html) ?? '';
        $html = preg_replace('/\{\{[\s\S]*?(?:\}\}|$)/', '', $html) ?? '';

        // Remove dangerous elements with their contents before allow-listing tags.
        $dangerous = 'script|style|iframe|object|embed|applet|form|input|textarea|select|option|link|meta|base|svg|math';
        $html = preg_replace('#<(' . $dangerous . ')\b[^>]*>[\s\S]*?</\1\s*>#i', '', $html) ?? '';
        $html = preg_replace('#<(' . $dangerous . ')\b[^>]*/?>#i', '', $html) ?? '';

        $allowed = '<' . implode('><', $this->allowedTags) . '>';
        $html = strip_tags($html, $allowed);

        // Remove event handlers and attributes capable of executing browser code.
        $html = preg_replace('/\s+on[a-z0-9_-]+\s*=\s*(?:"[^"]*"|\'[^\']*\'|[^\s>]+)/i', '', $html) ?? '';
        $html = preg_replace('/\s+(?:srcdoc|formaction|xlink:href)\s*=\s*(?:"[^"]*"|\'[^\']*\'|[^\s>]+)/i', '', $html) ?? '';
        $html = preg_replace_callback(
            '/\s+(href|src|poster)\s*=\s*(["\'])(.*?)\2/is',
            function (array $match): string {
                $value = html_entity_decode(trim($match[3]), ENT_QUOTES | ENT_HTML5, 'UTF-8');
                $normalized = strtolower(preg_replace('/[\x00-\x20]+/', '', $value) ?? '');

                if (Str::startsWith($normalized, ['javascript:', 'vbscript:', 'data:'])) {
                    return '';
                }

                return ' ' . strtolower($match[1]) . '=' . $match[2]
                    . htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') . $match[2];
            },
            $html
        ) ?? '';
        $html = preg_replace_callback(
            '/\s+(href|src|poster)\s*=\s*([^\s"\'=<>`]+)/i',
            function (array $match): string {
                $value = html_entity_decode(trim($match[2]), ENT_QUOTES | ENT_HTML5, 'UTF-8');
                $normalized = strtolower(preg_replace('/[\x00-\x20]+/', '', $value) ?? '');

                if (Str::startsWith($normalized, ['javascript:', 'vbscript:', 'data:'])) {
                    return '';
                }

                return ' ' . strtolower($match[1]) . '="'
                    . htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') . '"';
            },
            $html
        ) ?? '';

        // Inline style values are generated by the editor, but remove legacy CSS execution vectors.
        $html = preg_replace_callback(
            '/\s+style\s*=\s*(["\'])(.*?)\1/is',
            function (array $match): string {
                $style = $this->cssDeclarations($match[2]);
                return $style === '' ? '' : ' style="' . htmlspecialchars($style, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') . '"';
            },
            $html
        ) ?? '';
        $html = preg_replace('/\s+style\s*=\s*[^\s"\'=<>`]+/i', '', $html) ?? '';

        if ($dynamicTokens !== []) {
            $html = strtr($html, $dynamicTokens);
        }

        return trim($html) === '' ? null : trim($html);
    }

    /**
     * Sanitize the page-level CSS saved by the editor.
     */
    public function css(?string $css): ?string
    {
        if ($css === null || trim($css) === '') {
            return null;
        }

        $css = str_replace("\0", '', $css);
        $css = preg_replace('#/\*[\s\S]*?\*/#', '', $css) ?? '';
        $css = preg_replace('/@(?:import|charset|namespace)\b[^;]*(?:;|$)/i', '', $css) ?? '';
        $css = preg_replace('/(?:expression|javascript\s*:|vbscript\s*:|behavior\s*:|-moz-binding|data\s*:\s*text\/html)/i', '', $css) ?? '';
        $css = preg_replace('/url\s*\(\s*["\']?\s*(?!https?:|\/|\.\/|\.\.\/|data:image\/(?:png|jpe?g|gif|webp);base64,)[^)]+\)/i', 'none', $css) ?? '';
        $css = preg_replace('#</?(?:style|script)\b[^>]*>#i', '', $css) ?? '';

        return trim($css) === '' ? null : trim($css);
    }

    /**
     * Validate the editable JSON. It is not rendered directly, but keeping a constrained
     * schema prevents oversized/nested payloads from becoming an admin-side XSS vector.
     */
    public function design(?string $json): ?string
    {
        if ($json === null || trim($json) === '') {
            return null;
        }

        try {
            $data = json_decode($json, true, 64, JSON_THROW_ON_ERROR);
        } catch (\JsonException $exception) {
            throw new InvalidArgumentException('The page design is not valid JSON.', 0, $exception);
        }

        if (!is_array($data)) {
            throw new InvalidArgumentException('The page design must be a JSON object.');
        }

        $this->assertSafeDesignValue($data, 0);

        return json_encode(
            $data,
            JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_INVALID_UTF8_SUBSTITUTE
        );
    }

    private function cssDeclarations(string $style): string
    {
        $style = html_entity_decode($style, ENT_QUOTES | ENT_HTML5, 'UTF-8');
        $style = preg_replace('/(?:expression|javascript\s*:|vbscript\s*:|behavior\s*:|-moz-binding|data\s*:\s*text\/html)/i', '', $style) ?? '';
        $style = preg_replace('/url\s*\(\s*["\']?\s*(?!https?:|\/|\.\/|\.\.\/|data:image\/(?:png|jpe?g|gif|webp);base64,)[^)]+\)/i', 'none', $style) ?? '';
        $style = str_replace(['<', '>', '`'], '', $style);

        return trim($style);
    }

    private function assertSafeDesignValue(mixed $value, int $depth): void
    {
        if ($depth > 32) {
            throw new InvalidArgumentException('The page design is nested too deeply.');
        }

        if (is_array($value)) {
            if (count($value) > 1000) {
                throw new InvalidArgumentException('The page design contains too many items.');
            }

            foreach ($value as $key => $item) {
                if (is_string($key) && !preg_match('/^[a-zA-Z0-9_-]{1,80}$/', $key)) {
                    throw new InvalidArgumentException('The page design contains an invalid field name.');
                }
                $this->assertSafeDesignValue($item, $depth + 1);
            }
            return;
        }

        if (is_string($value)) {
            if (strlen($value) > 200000) {
                throw new InvalidArgumentException('A page design field is too large.');
            }
            if (preg_match('/<\s*script\b|<\?(?:php|=)|\bon[a-z]+\s*=/i', $value)) {
                throw new InvalidArgumentException('The page design contains executable content.');
            }
            return;
        }

        if (!is_null($value) && !is_bool($value) && !is_int($value) && !is_float($value)) {
            throw new InvalidArgumentException('The page design contains an unsupported value.');
        }
    }
}
